apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dump-env
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: dump-env
spec:
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/correlationid: https://github.com/cdelashmutt-pivotal/dump-env?sub_path=/
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"apps.tanzu.vmware.com/has-tests":"true","apps.tanzu.vmware.com/workload-type":"web"},"name":"dump-env","namespace":"chris"},"spec":{"build":{"env":[{"name":"BP_MAVEN_BUILT_ARTIFACT","value":"target/*-jar-with-dependencies.jar"}]},"env":[{"name":"JAVA_TOOL_OPTIONS","value":"-Dfoo=$DSC_VAL"},{"name":"DSC_VAL","valueFrom":{"secretKeyRef":{"key":"bar","name":"foo"}}}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/cdelashmutt-pivotal/dump-env"}}}}
      labels:
        app.kubernetes.io/component: run
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: dump-env
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: -Dfoo="$DSC_VAL"
        - name: DSC_VAL
          valueFrom:
            secretKeyRef:
              key: bar
              name: foo
        image: gcr.io/pa-cdelashmutt/cdd-demo-tap/workloads/dump-env-chris@sha256:cca7b05e4005864b4d9b933184e65af7e5883de7debecd7b6905cc2c2f4a3872
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

