apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: weatherforecast-steeltoe
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: weatherforecast-steeltoe
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.flavours: steeltoe
    tanzu.app.live.view.application.name: weatherforecast-steeltoe
    app.kubernetes.io/component: run
    carto.run/workload-name: weatherforecast-steeltoe
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          appliveview-sample/app-live-view-connector-steeltoe
          appliveview-sample/app-live-view-appflavours-steeltoe
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        apis.apps.tanzu.vmware.com/register-api: "true"
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: weatherforecast-steeltoe
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: weatherforecast-steeltoe
        tanzu.app.live.view: "true"
        tanzu.app.live.view.application.flavours: steeltoe
        tanzu.app.live.view.application.name: weatherforecast-steeltoe
    spec:
      containers:
      - image: gcr.io/pa-cdelashmutt/cdd-demo-tap/workloads/weatherforecast-steeltoe-dev@sha256:77304c689de399d6773e4a40fdc2446a4ead58abe9c745709e34e23699a880ca
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

