apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: weatherforecast-steeltoe
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: weatherforecast-steeltoe
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    kapp.k14s.io/app: "1687794778738191955"
    kapp.k14s.io/association: v1.836da03faf3f6c04838b4f93d8e32285
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.flavours: steeltoe
    tanzu.app.live.view.application.name: weatherforecast-steeltoe
    app.kubernetes.io/component: run
    carto.run/workload-name: weatherforecast-steeltoe
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          appliveview-sample/app-live-view-connector-steeltoe
          appliveview-sample/app-live-view-appflavours-steeltoe
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        kapp.k14s.io/identity: v1;dev/carto.run/Workload/weatherforecast-steeltoe;carto.run/v1alpha1
      labels:
        apis.apps.tanzu.vmware.com/register-api: "true"
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: weatherforecast-steeltoe
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: weatherforecast-steeltoe
        kapp.k14s.io/app: "1687794778738191955"
        kapp.k14s.io/association: v1.836da03faf3f6c04838b4f93d8e32285
        tanzu.app.live.view: "true"
        tanzu.app.live.view.application.flavours: steeltoe
        tanzu.app.live.view.application.name: weatherforecast-steeltoe
    spec:
      containers:
      - image: gcr.io/pa-cdelashmutt/cdd-demo-tap/workloads/weatherforecast-steeltoe-dev@sha256:32ba2ce9057fd8aa20b08b11b58dee0cdabcfbe91a4b9aded42438a98b3eb10a
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

