apiVersion: kapp.k14s.io/v1alpha1
kind: Config
waitRules:
- conditionMatchers:
  - type: ServiceAvailable
    status: "False"
    failure: true
  - type: ServiceAvailable
    status: "True"
    success: true
  resourceMatchers:
  - apiVersionKindMatcher:
      apiVersion: servicebinding.io/v1alpha3
      kind: ServiceBinding
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: appsso-starter-java-appsso-starter-java
  annotations:
    kapp.k14s.io/identity: v1;dev/carto.run/Workload/appsso-starter-java;carto.run/v1alpha1
    kapp.k14s.io/original: '{"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"labels":{"app.kubernetes.io/part-of":"appsso-starter-java","apps.tanzu.vmware.com/auto-configure-actuators":"true","apps.tanzu.vmware.com/has-tests":"true","apps.tanzu.vmware.com/workload-type":"web","kapp.k14s.io/app":"1687794778738191955","kapp.k14s.io/association":"v1.49c8fa80bd589bafaaeaf66931c87800"},"name":"appsso-starter-java","namespace":"dev"},"spec":{"build":{"env":[{"name":"BP_JVM_VERSION","value":"17"}]},"params":[{"name":"live-update","value":"true"}],"serviceClaims":[{"name":"appsso-starter-java","ref":{"apiVersion":"services.apps.tanzu.vmware.com/v1alpha1","kind":"ClassClaim","name":"appsso-starter-java"}}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/cdelashmutt-pivotal/appsso-starter-java"}}}}'
    kapp.k14s.io/original-diff-md5: c6e94dc94aed3401b5d0f26ed6c0bff3
    kapp.k14s.io/change-group: servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: appsso-starter-java
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    kapp.k14s.io/app: "1687794778738191955"
    kapp.k14s.io/association: v1.49c8fa80bd589bafaaeaf66931c87800
    app.kubernetes.io/component: run
    carto.run/workload-name: appsso-starter-java
spec:
  name: appsso-starter-java
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ClassClaim
    name: appsso-starter-java
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: appsso-starter-java

